How to set up a third party contract vendor
linuxfoundation/devex-and-commsuccess pull request #20
Opened 2022-08-01 19:51 UTC by cmassey11

Added content to the handbook.

Signed-off-by: Claire Massey (Linux Foundation) <cmassey@linuxfoundation.org>

2022-08-01 19:59 UTC, wendallkaters commented on README.md
> +How to set up a third party contract vendor (agency or individual):
Does these need to be a header for it to go in the TOC?

2022-08-02 10:00 UTC, dplanella commented on README.md
> +#How to set up a third party contract vendor (agency or individual):
```suggestion
## How to set up a third party contract vendor

These steps apply to either agencies or individuals.
```
Thanks! I'm proposing some changes:

- Add space between `#` and title for proper Markdown formatting
- Make the title a Header 2 level for consistency with the rest of the document (`##`)
- Shorten the title, move the extra info below the title.

@cmassey11 if you're happy with the changes, please feel free to accept the suggestion. Thanks!

2022-08-02 10:06 UTC, dplanella commented on README.md
> +How to set up a third party contract vendor (agency or individual):
Good catch, I've added a suggestion to address this at https://github.com/linuxfoundation/devex-and-commsuccess-handbook/pull/20#pullrequestreview-1058497211

2022-08-02 10:16 UTC, dplanella requested changes
I've added some suggestions for additional changes before approval. In summary, the list's indentation needs to be fixed for it to be displayed correctly in Markdown.

2022-08-02 10:16 UTC, dplanella commented on README.md
> +    1. Creates a scope of work (SOW) outlining what they will be doing and what it will cost. This is the preferred method.
```suggestion
   1. Creates a scope of work (SOW) outlining what they will be doing and what it will cost. This is the preferred method. 
```
Nested lists need to be indented at the level of the first letter of the list item above.

2022-08-02 10:16 UTC, dplanella commented on README.md
> +    3. In order to complete the form you will need this information from the contractor:
```suggestion
   1. In order to complete the form you will need this information from the contractor:
```
- Fix indentation to align to previous list item
- Consider using [lazy numbering](https://google.github.io/styleguide/docguide/style.html#use-lazy-numbering-for-long-lists). In summary, you can use `1.` for all items in the numbered list.

2022-08-02 10:17 UTC, dplanella commented on README.md
> +    3. In order to complete the form you will need this information from the contractor:
This comment applies to all list items below, which will also need to be changed.

2022-08-02 20:54 UTC, dplanella submitted a review, later dismissed
@cmassey11 thank you. I added some more suggestions where the rest of the list items indentation needed to be fixed. Please review the suggestions.

2022-08-02 20:54 UTC, dplanella commented on README.md
> +    2. Creates a legal agreement that includes a SOW. This method requires the LF Legal team to review the contract before approving it for LF to sign.
```suggestion
   1. Creates a legal agreement that includes a SOW. This method requires the LF Legal team to review the contract before approving it for LF to sign. 
```
Fix Markdown indentation, use [lazy numbering](https://google.github.io/styleguide/docguide/style.html#use-lazy-numbering-for-long-lists)

2022-08-02 20:54 UTC, dplanella commented on README.md
> +        16. Scope of work provided by the vendor (provided as an attachment)
```suggestion
   1. Vendor name
   1. Name of signatory for contract
   1. Email address of signatory for contract
   1. Contractor’s physical mailing address
   1. Contractor start date
   1. Contractor duration
   1. Contractor type: individual or agency
   1. New contract or extension to an existing contractor agreement (requires LF Legal review)
   1. Standard LF contract (preferred) or 
   1. LF department or Project the contractor will be working for
   1. Description of work to align it with the correct budget code (ex: Marketing)
   1. Compensation type: hourly, salary, other
   1. Compensation amount
   1. Compensation max budget
   1. Name of LF internal manager
   1. Scope of work provided by the vendor (provided as an attachment)
```

Fix Markdown indentation, use [lazy numbering](https://google.github.io/styleguide/docguide/style.html#use-lazy-numbering-for-long-lists)

2022-08-02 20:54 UTC, dplanella commented on README.md
> +    6. Finally it is sent to the contract vendor for them to sign.
```suggestion
   1. The Docusign agreement is first sent to the Finance lead for that department or project for them to sign. 
   1. It is then routed to the LF internal manager (who will manage the contractor) for them to sign.
   1. Finally it is sent to the contract vendor for them to sign.
```
Fix Markdown indentation, use [lazy numbering](https://google.github.io/styleguide/docguide/style.html#use-lazy-numbering-for-long-lists)

2022-08-04 16:21 UTC, jmertic commented on README.md
> +
@cmassey11 Should this addition be a seperate document instead of in the main README?

2022-08-04 18:30 UTC, ncaidin commented
Hello @cmassey11 , I notice on point 7 there is some weird numbering happening within the paragraph:
"Once approved by LF Finance, The LF HR Finance Ops team will create a Docusign agreement. You will receive a notification that the agreement is “out for signature” when it is sent to the first signatory. 4. The Docusign agreement is first sent to the Finance lead for that department or project for them to sign. 5. It is then routed to the LF internal manager (who will manage the contractor) for them to sign. 6. Finally it is sent to the contract vendor for them to sign."

Is the 4, 5, and 6 supposed to be in there?

2022-08-06 05:52 UTC, dplanella commented on README.md
> +    2. Creates a legal agreement that includes a SOW. This method requires the LF Legal team to review the contract before approving it for LF to sign.
This was resolved after addressing the merge conflict.

2022-08-06 05:52 UTC, dplanella commented on README.md
> +        16. Scope of work provided by the vendor (provided as an attachment)
This was resolved after addressing the merge conflict.

2022-08-06 05:53 UTC, dplanella commented on README.md
> +    6. Finally it is sent to the contract vendor for them to sign.
This was resolved after addressing the merge conflict.

2022-08-06 05:58 UTC, dplanella commented on README.md
> +
Good point. We'll have to start planning the handbook structure sooner than later. For now, in the spirit of iteration, let's land this change. After it's in the handbook, Claire can decide whether it needs to live in a separate page.

2022-08-06 05:58 UTC, merged