Update README.md
linuxfoundation/devex-and-commsuccess pull request #45
Opened 2022-08-16 20:13 UTC by ncaidin

Adding a section on How to Change Member roles on a project. This is a fairly common request as people join companies, leave companies, and change roles within companies. Sometimes a person has not changed roles within their organization but the role has changed with respect to the project.

Signed-off-by: Neal Caidin <ncaidin@linuxfoundation.org>

2022-08-16 20:24 UTC, dplanella requested changes
Thanks Neil! I've added a couple of comments/questions after my review. Could you please address them before we merge?

2022-08-16 20:24 UTC, dplanella commented on README.md
> +1. Encourage members to use the [Member Support Desk](https://docs.google.com/document/d/1NHPRGfcyg8FVNlRC9-HX-hOIYbafXxtu5Bie3wNCvSg/edit?usp=sharing) to report changes in project roles. This is the
@ncaidin if the preferred method is the Member Support Desk,

1. Is there a reason for also suggesting to use the Staff portal?
2. What would be a legitimate use case to use the Staff portal instead of the Member Support desk?

2022-08-16 20:24 UTC, dplanella commented on README.md
> +3. LF Operations will notify the LF prime for the project. The LF Prime updates the Project Control Center ([PCC](https://docs.linuxfoundation.org/lfx/project-control-center-pre-release)) and the [Or
This might be the non-native speaker in me: what is a `prime`?

2022-08-16 20:25 UTC, dplanella commented
@ncaidin if you're ready for review, you might want to unmark this PR as a draft, with the <kbd>Ready for review</kbd> button.

2022-08-17 00:55 UTC, ncaidin commented
@dplanella , I made it draft intentionally so that I could come back and work on it some more. Is that the wrong way to do that?

2022-08-17 08:07 UTC, dplanella commented
> @dplanella , I made it draft intentionally so that I could come back and work on it some more. Is that the wrong way to do that?

There is no right or wrong way, we simply need to agree on how we use the Draft feature. Generally, if you are working on a draft, and as it's considered work in progress, you don't assign reviewers. The reason being, you don't want people to review things that you are planning to change, which will require then a subsequent review. In general, when you work on a draft, you do your changes until they are ready for review, then you mark it as such, and then you add reviewers to review and ultimately merge.

There are valid use cases for assigning reviewers to a Draft PR though. For instance, when you want early feedback to ensure the change is going in the right direction early enough in the process, to avoid having to course-correct bigger changes further down the review process.

All in all, we should simply agree on the review workflow for our team and ultimately document all aspects at https://github.com/linuxfoundation/devex-and-commsuccess/tree/main/how-to-edit-the-handbook

Let me know if this makes sense.

2022-08-17 11:38 UTC, ncaidin commented
To be honest, I did not intend to assign any reviewers! Rookie mistake. I'm not even sure how that happened. I was not looking to assign reviewers.

2022-08-17 11:44 UTC, ncaidin commented on README.md
> +1. Encourage members to use the [Member Support Desk](https://docs.google.com/document/d/1NHPRGfcyg8FVNlRC9-HX-hOIYbafXxtu5Bie3wNCvSg/edit?usp=sharing) to report changes in project roles. This is the
> 1. Is there a reason for also suggesting to use the Staff portal?
Because the Operations group is collecting metrics. If for some reason the PM decides they will make this change, then we want to make sure they do it through the Staff portal rather than the Member Support Desk. 

>2. What would be a legitimate use case to use the Staff portal instead of the Member Support desk?
If the Member asks you to help them, could be one use case. Another could be where the PM spots a mistake and already knows it is a mistake on the LF side. Rather than notify the Member, we could just get it fixed. That could be another use case.

2022-08-17 11:48 UTC, ncaidin commented on README.md
> +3. LF Operations will notify the LF prime for the project. The LF Prime updates the Project Control Center ([PCC](https://docs.linuxfoundation.org/lfx/project-control-center-pre-release)) and the [Or
I could have used "PM" in this spot for Program Manager, but I was thinking that we have several different titles in our group. LF Prime means the main contact, whoever that is and whatever role they have. Prime means main. It has the same root as primary. I'm open to other options (like PM). Any suggestions?

2022-08-17 12:21 UTC, dplanella commented on README.md
> +1. Encourage members to use the [Member Support Desk](https://docs.google.com/document/d/1NHPRGfcyg8FVNlRC9-HX-hOIYbafXxtu5Bie3wNCvSg/edit?usp=sharing) to report changes in project roles. This is the
Thanks for the clarification. This answer below does not yet make sense to me. Could you please elaborate?

> Is there a reason for also suggesting to use the Staff portal? Because the Operations group is collecting metrics. 

I'd suggest to emphasize that the Staff portal should be an exception that requires a specific justification, and to document these use cases in the handbook:

> What would be a legitimate use case to use the Staff portal instead of the Member Support desk?
Another could be where the PM spots a mistake and already knows it is a mistake on the LF side. Rather than notify the Member, we could just get it fixed. That could be another use case.

On the case below,

> If the Member asks you to help them, could be one use case.

Is this (members e-mailing PMs) specifically not something we want to avoid, and the reason of existence of the Member Support desk?

2022-08-17 12:24 UTC, dplanella commented on README.md
> +3. LF Operations will notify the LF prime for the project. The LF Prime updates the Project Control Center ([PCC](https://docs.linuxfoundation.org/lfx/project-control-center-pre-release)) and the [Or
Thanks. My suggestions would be to:

1. Use a either a more common term that is fully descriptive (e.g. LF Primary Contact), or standardize on whichever term LFX uses for this person.
1. Document this role in the https://github.com/linuxfoundation/devex-and-commsuccess#acronym-glossary section

2022-08-25 13:41 UTC, ncaidin commented on README.md
> +1. Encourage members to use the [Member Support Desk](https://docs.google.com/document/d/1NHPRGfcyg8FVNlRC9-HX-hOIYbafXxtu5Bie3wNCvSg/edit?usp=sharing) to report changes in project roles. This is the
Okay, I will clarify in the text that the preferred way is the Member Support Desk and that exceptions should be documented in the handbook.

2022-08-25 13:44 UTC, ncaidin commented on README.md
> +3. LF Operations will notify the LF prime for the project. The LF Prime updates the Project Control Center ([PCC](https://docs.linuxfoundation.org/lfx/project-control-center-pre-release)) and the [Or
@dplanella , it looks like the term in PCC is "project administrator". How about we go with that?

2022-08-29 14:26 UTC, jzcardoso reviewed
This looks correct to me.

2022-08-29 15:21 UTC, dplanella commented on README.md
> +3. LF Operations will notify the LF prime for the project. The LF Prime updates the Project Control Center ([PCC](https://docs.linuxfoundation.org/lfx/project-control-center-pre-release)) and the [Or
@ncaidin sounds great, +1

2022-08-30 17:23 UTC, dplanella approved these changes

2022-08-30 17:23 UTC, merged